### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Maziar123** [jbaldwin/libcoro#112]
I Try build on Linux gcc 11.2 :

In file included from /usr/include/signal.h:328,
                 from /mnt/N1/MZ/Prog/PC_CPP/CppLibs/libcoro/test/catch.hpp:7955,
                 from /mnt/N1/MZ/Prog/PC_CPP/CppLibs/libcoro/test/main.cpp:2:
/mnt/N1/MZ/Prog/PC_CPP/CppLibs/libcoro/test/catch.hpp:10735:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
10735 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/c++/11.2.0/bits/atomic_wait.h:44,
                 from /usr/include/c++/11.2.0/bits/atomic_base.h:41,
                 from /usr/include/c++/11.2.0/bits/shared_ptr_atomic.h:33,
                 from /usr/include/c++/11.2.0/memory:78,
                 from /mnt/N1/MZ/Prog/PC_CPP/CppLibs/libcoro/test/catch.hpp:2909,
                 from /mnt/N1/MZ/Prog/PC_CPP/CppLibs/libcoro/test/main.cpp:2:
/usr/include/unistd.h:640:17: note: ‘long int sysconf(int)’ declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from /mnt/N1/MZ/Prog/PC_CPP/CppLibs/libcoro/test/main.cpp:2:
/mnt/N1/MZ/Prog/PC_CPP/CppLibs/libcoro/test/catch.hpp:10794:45: error: size of array ‘altStackMem’ is not an integral constant-expression
10794 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~
ninja: build stopped: subcommand failed.

**Comment by jbaldwin** [comment]
Looks like its time to upgrade catch2, I currently only have gcc 11.1 on my local box so might take some time to reproduce.

**Comment by jbaldwin** [comment]
@Maziar123 I've updated #113 but I didn't have time to try on the latest compiler.  Mind giving it another whirl and see if this fixes your issue?

**Comment by jbaldwin** [comment]
I'm going to go ahead and close this out, if you are still having issues please re-open
